name = "Move"
grammar = "move_on_aptos"
path_suffixes = ["move"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
autoclose_before = "]},)>\"' \n\t"
word_characters = ["_"]

# Bracket pairs for auto-closing
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
